#!/bin/bash
ppm2svg() {
  if [ -e "$(dirname $0)/braille" ] ; then
    ex=$((6 * 2));
    em=$((8 * 2));
    # echo "em: $em; ex: $ex";
    w=`tail -n1 $2 | wc -w  | awk -v ex=$ex '{print (($1 * ex))}'`
    h=`wc -l $2 | awk -v em=$em '{print ((($1 - 3) * em))}'`
    echo "<svg viewBox=\"0 0 $w $h\"><text x=\"0\" y=\"0\">$($(dirname $0)/braille -l "$1" "$2")</text></svg>" > "$3";
    # echo "<svg viewBox=\"0 0 $w $h\"><text x=\"0\" y=\"0\">$($(dirname $0)/braille "$1" | while IFS= read -r line ; do echo "<tspan x=\"0\" dy=\"1.2em\">$line</tspan>"; done;)</text></svg>" > "$2";
    return 0;
  fi;
  throw "Required software is not found
    You can install it with following command:
      brew install imagemagick";
}
